### ISSUE TITLE
mcpe command does not respect port number

### ISSUE THREAD

**Issue by edward3h** [MisteFr/BedrockUpdateBot#6]
![bedrockupdatebot_port](https://user-images.githubusercontent.com/899118/89421849-8e911280-d702-11ea-9932-1853ef575981.png)

I have 3 BDS servers running on different port numbers. 19132 (default), 19134, 19136

There are two issues:
1. The help text says ">mcpe <ip:port>" but the colon ":" does not work. (The code splits on a space)
2. Even if I use a space, the non-default port is not honoured, I get the status for 19132. Looks like mcpe-ping is expecting the port to be a Number and it ignores it otherwise.

**Comment by edward3h** [comment]
I can work on a fix for this but probably not for a few days.

**Comment by MisteFr** [comment]
Fixed, thanks for the report!
